imports:
    - { resource: tables.yml }

services:
    forumhulp.referrers.listener:
        class: forumhulp\referrers\event\listener
        arguments:
            - @config
            - @controller.helper
            - @user
            - @dbal.conn
            - %tables.referrers%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    forumhulp.referrers:
        class: forumhulp\referrers\cron\task\core\delete_referrers
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @user
            - @log
            - @dbal.conn
            - %tables.referrers%

        calls:
            - [set_name, [forumhulp.referrers]]
        tags:
            - { name: cron.task }
